/**
 * Task and Workflow Period Type Definitions
 * These types are used throughout the application for task management
 * All actual data comes from Supabase database
 */

export interface WorkflowPeriod {
  id: string
  name: string
  displayName: string
  startTime: string
  endTime: string
  isEventDriven?: boolean  // 标记是否为事件驱动的时段
  tasks: {
    manager: TaskTemplate[]
    chef: TaskTemplate[]
    dutyManager?: TaskTemplate[]  // 值班经理任务
  }
}

export interface TaskTemplate {
  id: string
  title: string
  description: string
  isNotice?: boolean
  role: 'Manager' | 'Chef' | 'DutyManager'
  department: '前厅' | '后厨'
  uploadRequirement?: '拍照' | '录音' | '记录' | '列表' | '审核' | null
  timeSlot?: string  // Optional, for display purposes
  startTime?: string // Optional, for display purposes
  endTime?: string   // Optional, for display purposes
  isFloating?: boolean      // 标识为浮动任务
  floatingType?: 'daily' | 'anytime'  // daily=每天一次，anytime=随时可做
  prerequisiteFor?: string[] // 作为哪些时间段的前置条件
  prerequisiteTrigger?: 'last-customer-left-lunch' | 'last-customer-left-dinner'  // 触发条件
  linkedTasks?: string[]  // 审核任务关联的任务ID列表
  autoGenerated?: boolean  // 标记是否为自动生成的任务
  manualClosing?: boolean  // 标识是否为手动闭店任务
  samples?: {
    samples: Array<{
      index: number
      text: string
      images: string[]
      checklist?: {
        items: string[]
      }
    }>
  } | null  // samples结构，包含分组的文本、图片和checklist
  structuredFields?: any  // 结构化字段配置，用于收货验货等需要规范化输入的任务
}